package com.greg.cart.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Data
@Document(collection = "carts")
public class Cart {
    @Id
    private String id; // Auto-generated by MongoDB
    private String userId;
    private List<CartItem> items = new ArrayList<>();

    @Data
    public static class CartItem {
        private String productId;
        private String productName;
        private int quantity;
        private double price;
    }
}