package com.greg.cart.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Data
@Document(collection = "carts")
public class Cart {
    @Id
    private String id; // Auto-generated by MongoDB
    private String userId;
    private List<CartItem> items = new ArrayList<>();
    @Transient
    @JsonProperty("subTotal")
    public double getSubTotal() {
        double sum = items.stream()
                .mapToDouble(item -> item.getPrice() * item.getQuantity())
                .sum();
        return Math.round(sum * 100.0) / 100.0; // Round to 2 decimal places
    }

    @Transient
    @JsonProperty("itemCount")
    public int getItemCount() {
        return items.stream()
                .mapToInt(CartItem::getQuantity)
                .sum();
    }
    @Data
    public static class CartItem {
        private String productId;
        private String productName;
        private int quantity;
        private double price;
    }
}